In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.datasets as datasets
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
import torch.nn.functional as F
from tqdm import tqdm
from cnn_models import LeNet
from PCLeNet import PCLeNet
from CustomDataset import PreloadedDataset
from train_loops import train, train_pc
from my_funcs import RandomGaussianNoise

In [68]:
#  SpearMax
x = torch.rand(4,2,2)
print(x)
x = x.argmax(dim=0)
print(x)
x = F.one_hot(x, 4).transpose(2,1).transpose(1,0)
x

tensor([[[0.2210, 0.8962],
         [0.8571, 0.4833]],

        [[0.5902, 0.2014],
         [0.5777, 0.5776]],

        [[0.0680, 0.7574],
         [0.5303, 0.2064]],

        [[0.0351, 0.3617],
         [0.3685, 0.0249]]])
tensor([[1, 0],
        [0, 1]])


tensor([[[0, 1],
         [1, 0]],

        [[1, 0],
         [0, 1]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]])

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
VAL_RATIO = 0.2

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.RandomHorizontalFlip(p=0.5),
    RandomGaussianNoise(std=0.001),
    transforms.RandomAffine(degrees=35, translate=(0.15,0.15), scale=(0.90,1.10)),
])

dataset = datasets.MNIST(root="../../../datasets/", train=True, transform=transforms.ToTensor(), download=True)
val_len = int(len(dataset) * VAL_RATIO)
train_len = len(dataset) - val_len
# print(dataset[0][1])
train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_len, val_len])
train_dataset = PreloadedDataset.from_dataset(train_dataset, transform, device)
val_dataset = PreloadedDataset.from_dataset(val_dataset, transforms.ToTensor(), device)

In [12]:
#  Standard LeNet CNN
model_name = "LeNet"
LEARNING_RATE = 3e-4
lenet = LeNet().to(device)
criterion = nn.CrossEntropyLoss()
optimiser = optim.AdamW(lenet.parameters(), lr=LEARNING_RATE)
cnn_train_loss, cnn_train_acc, cnn_val_loss, cnn_val_acc, _ = train(
    lenet,
    train_dataset,
    val_dataset,
    optimiser,
    criterion,
    model_name,
    30,
    log_dir="MNIST",
    device=device,
)

In [12]:
torch.manual_seed(0)
model_name="PCLeNetAdamW_BS500_DataAug"
LEARNING_RATE = 3e-4
criterion = nn.CrossEntropyLoss()
pclenet = PCLeNet().to(device)
optimiser = optim.AdamW(pclenet.parameters())
optimiser.lr=LEARNING_RATE
pccnn_train_loss, pccnn_train_acc, pccnn_val_loss, pccnn_val_acc, step = train_pc(
    pclenet,
    train_dataset,
    val_dataset,
    optimiser,
    criterion,
    model_name,
    100,
    batch_size=500,
    log_dir="MNIST",
    device=device,
    save_model=True,
    step=0
)

In [13]:
torch.manual_seed(0)
model_name="PCLeNetAdamW_BS500_DataAug_LR=3e-3"
LEARNING_RATE = 3e-3
criterion = nn.CrossEntropyLoss()
pclenet = PCLeNet().to(device)
optimiser = optim.AdamW(pclenet.parameters())
optimiser.lr=LEARNING_RATE
pccnn_train_loss, pccnn_train_acc, pccnn_val_loss, pccnn_val_acc, step = train_pc(
    pclenet,
    train_dataset,
    val_dataset,
    optimiser,
    criterion,
    model_name,
    100,
    batch_size=500,
    log_dir="MNIST",
    device=device,
    save_model=True,
    step=0
)

In [14]:
torch.manual_seed(0)
model_name="PCLeNetAdamW_BS500_DataAug_LR=3e-3Sch2"
LEARNING_RATE = 3e-3
criterion = nn.CrossEntropyLoss()
pclenet = PCLeNet().to(device)
optimiser = optim.AdamW(pclenet.parameters())
optimiser.lr=LEARNING_RATE
pccnn_train_loss, pccnn_train_acc, pccnn_val_loss, pccnn_val_acc, step = train_pc(
    pclenet,
    train_dataset,
    val_dataset,
    optimiser,
    criterion,
    model_name,
    30,
    batch_size=500,
    log_dir="MNIST",
    device=device,
    save_model=True,
    step=0
)

optimiser.lr=3e-4
pccnn_train_loss, pccnn_train_acc, pccnn_val_loss, pccnn_val_acc, step = train_pc(
    pclenet,
    train_dataset,
    val_dataset,
    optimiser,
    criterion,
    model_name,
    70,
    batch_size=500,
    log_dir="MNIST",
    device=device,
    save_model=True,
    step=step
)

In [15]:

torch.manual_seed(0)
model_name="PCLeNetAdamW_BS500_DataAug_LR=3e-3Sch3"
LEARNING_RATE = 3e-3
criterion = nn.CrossEntropyLoss()
pclenet = PCLeNet().to(device)
optimiser = optim.AdamW(pclenet.parameters())
optimiser.lr=LEARNING_RATE
pccnn_train_loss, pccnn_train_acc, pccnn_val_loss, pccnn_val_acc, step = train_pc(
    pclenet,
    train_dataset,
    val_dataset,
    optimiser,
    criterion,
    model_name,
    30,
    batch_size=500,
    log_dir="MNIST",
    device=device,
    save_model=True,
    step=0
)

optimiser.lr=3e-4
pccnn_train_loss, pccnn_train_acc, pccnn_val_loss, pccnn_val_acc, step = train_pc(
    pclenet,
    train_dataset,
    val_dataset,
    optimiser,
    criterion,
    model_name,
    30,
    batch_size=500,
    log_dir="MNIST",
    device=device,
    save_model=True,
    step=step
)

optimiser.lr=3e-5
pccnn_train_loss, pccnn_train_acc, pccnn_val_loss, pccnn_val_acc, step = train_pc(
    pclenet,
    train_dataset,
    val_dataset,
    optimiser,
    criterion,
    model_name,
    40,
    batch_size=500,
    log_dir="MNIST",
    device=device,
    save_model=True,
    step=step
)